# Generated by Django 4.0.3 on 2022-03-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyrecord',
            name='premium',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='policyrecord',
            name='sum_assurance',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
