# Generated by Django 4.0.3 on 2022-03-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_alter_policy_options_remove_policy_tenure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceeventrecord',
            name='status',
            field=models.CharField(default='Přijato', max_length=100),
        ),
    ]
