# Generated by Django 4.0.3 on 2022-03-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mail',
            field=models.CharField(default='a@b.c', max_length=50),
        ),
    ]
